@startuml
actor Arzt
participant Türsystem
participant Scanner
participant "Apotheken-Computer"

Arzt -> Türsystem : PIN eingeben
Türsystem -> Arzt : Zugang prüfen
Türsystem -> Arzt : Tür öffnet sich

== Arzt entnimmt Medikamente ==

Arzt -> "Scanner" : Medikamente scannen
"Scanner" -> "Apotheken-Computer" : Barcode-Daten senden
"Apotheken-Computer" -> "Apotheken-Computer" : Medikament zu Praxiskonto zuordnen
"Apotheken-Computer" -> Arzt : Bestätigung anzeigen

@enduml